version: '3.8'
services:
  backend:
    build: ./Backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: development
    restart: unless-stopped
  frontend:
    build: ./Frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
